CREATE TABLE movies(
  movie_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR,
  runtime_in_minutes INT,
  rating VARCHAR,
  description TEXT,
  image_url VARCHAR,
  created_at DATE,
  updated_at DATE
);