CREATE TABLE theaters(
  theater_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR,
  address_line_1 VARCHAR,
  address_line_2 VARCHAR,
  city VARCHAR,
  state VARCHAR,
  zip VARCHAR
);